#!/usr/bin/env python3
"""
Reads permissions/permissions.yaml and writes:
  backend/apps/rbac/permissions_registry.py
  frontend/src/lib/permissions.ts

Run from repo root: python permissions/generate.py
CI: python permissions/generate.py && git diff --exit-code
"""
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml not installed — run: pip install pyyaml")

ROOT = Path(__file__).parent.parent
YAML_FILE = Path(__file__).parent / "permissions.yaml"
PY_OUT = ROOT / "backend" / "apps" / "rbac" / "permissions_registry.py"
TS_OUT = ROOT / "frontend" / "src" / "lib" / "permissions.ts"


def to_const(code: str) -> str:
    return code.upper().replace(".", "_")


def generate_python(perms: list) -> str:
    lines = [
        "# AUTO-GENERATED by permissions/generate.py — do not edit by hand.",
        "# Edit permissions/permissions.yaml then re-run the script.",
        "from dataclasses import dataclass",
        "from typing import List, NewType",
        "",
        "# Opaque string type — mypy rejects plain str where PermCode is expected.",
        "# At runtime NewType is transparent (just the underlying str), but CI mypy",
        "# catches has_permission(user, 'some.literal') as a type error.",
        "PermCode = NewType('PermCode', str)",
        "",
        "",
        "@dataclass(frozen=True)",
        "class Perm:",
        "    code: str",
        "    description: str",
        "    sensitive: bool = False",
        "    category: str = ''",
        "",
        "",
        "# Import these constants instead of hardcoding permission strings.",
        "# They are PermCode, not plain str — passing a raw string literal to",
        "# has_permission() is a mypy error.",
    ]

    for p in perms:
        lines.append(f"{to_const(p['code'])} = PermCode('{p['code']}')")

    lines += ["", "", "REGISTRY: List[Perm] = ["]
    for p in perms:
        lines.append(
            f"    Perm(code={to_const(p['code'])}, "
            f"description={p['description']!r}, "
            f"sensitive={p['sensitive']}, "
            f"category={p['category']!r}),"
        )
    lines += [
        "]",
        "",
        "REGISTRY_MAP = {p.code: p for p in REGISTRY}",
        "",
        "",
        "def sync_permissions():",
        "    \"\"\"Materialize REGISTRY into the Permission table. Convergent — safe to run repeatedly.\"\"\"",
        "    from .models import Permission",
        "    existing = set(Permission.objects.values_list('code', flat=True))",
        "    to_create = [",
        "        Permission(code=p.code, description=p.description)",
        "        for p in REGISTRY if p.code not in existing",
        "    ]",
        "    if to_create:",
        "        Permission.objects.bulk_create(to_create, ignore_conflicts=True)",
        "",
    ]
    return "\n".join(lines)


def generate_typescript(perms: list) -> str:
    lines = [
        "// AUTO-GENERATED by permissions/generate.py — do not edit by hand.",
        "// Edit permissions/permissions.yaml then re-run the script.",
        "",
        "export const PERMS = {",
    ]
    for p in perms:
        lines.append(f"  {to_const(p['code'])}: '{p['code']}',")
    lines += [
        "} as const",
        "",
        "export type PermKey = (typeof PERMS)[keyof typeof PERMS]",
        "",
        "export interface PermMeta {",
        "  code: PermKey",
        "  label: string",
        "  description: string",
        "  sensitive: boolean",
        "  category: string",
        "}",
        "",
        "export const PERM_META: PermMeta[] = [",
    ]
    for p in perms:
        sensitive_str = "true" if p["sensitive"] else "false"
        lines.append(
            f"  {{ code: '{p['code']}', label: '{p['label']}', "
            f"description: '{p['description']}', sensitive: {sensitive_str}, "
            f"category: '{p['category']}' }},"
        )
    lines += ["]", ""]
    return "\n".join(lines)


def main():
    with open(YAML_FILE) as f:
        perms = yaml.safe_load(f)

    py_content = generate_python(perms)
    ts_content = generate_typescript(perms)

    PY_OUT.write_text(py_content, encoding="utf-8")
    TS_OUT.write_text(ts_content, encoding="utf-8")

    print(f"wrote {PY_OUT.relative_to(ROOT)}")
    print(f"wrote {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
